# Generated by Django 4.1.6 on 2023-02-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_task_end_time_alter_task_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='foydalanuvchi_fk',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('st_raqam', models.CharField(max_length=7)),
                ('kurs', models.PositiveIntegerField()),
                ('foydalanuvchi_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='talaba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
    ]
