# Generated by Django 4.1.6 on 2023-02-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_task_foydalanuvchi_fk_alter_task_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='foydalanuvchi_fk',
            new_name='f_fk',
        ),
    ]
